// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzrqmoxebsewdfnnnhpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56cnFtb3hlYnNld2Rmbm5uaHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDExMjYsImV4cCI6MjA2Nzg3NzEyNn0.-t7KC3sNa_X_uXcDnOyv2yRa4FKRD5-VCAQ4St7j47c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});